<div class="py-16 sm:py-24 bg-gray-50 flex items-center justify-center flex-grow animate-fade-in">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8 w-full">
        <!-- Header -->
        <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
            <div>
                <h1 class="text-3xl font-extrabold tracking-tight text-gray-900">Research Reports Gallery</h1>
                <p class="mt-2 text-sm text-gray-500 max-w-2xl">Browse public marketing and opinion audits generated by the Metrica Research analysis team.</p>
            </div>
            @if($selectedReportId)
                <button wire:click="closeReport" class="rounded-md border border-gray-300 bg-white px-4 py-2 text-xs font-semibold text-gray-700 hover:border-gray-950 transition">
                    &larr; Back to Gallery
                </button>
            @endif
        </div>

        @if (session()->has('success'))
            <div class="p-4 bg-green-50 border border-green-200 text-green-700 text-sm rounded-md">
                {{ session('success') }}
            </div>
        @endif

        @if(!$selectedReportId)
            <!-- 1. GRID VIEW OF REPORTS -->
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                @forelse($polls as $poll)
                    <div wire:click="selectReport({{ $poll->id }})" class="bg-white border border-gray-200 rounded-lg p-6 shadow-sm hover:shadow-md hover:border-gray-950 transition duration-150 cursor-pointer flex flex-col justify-between space-y-4">
                        <div class="space-y-3">
                            <span class="inline-flex items-center rounded-md bg-gray-50 px-2 py-0.5 text-xxs font-medium text-gray-600 ring-1 ring-inset ring-gray-500/10 uppercase tracking-wide">
                                {{ $poll->category }}
                            </span>
                            <h2 class="text-base font-bold text-gray-950 leading-snug line-clamp-2">{{ $poll->title }}</h2>
                            
                            <div class="text-xxs text-gray-500 space-y-1">
                                <div><strong>Region:</strong> {{ $poll->region ?? 'N/A' }}</div>
                                <div><strong>Released:</strong> {{ $poll->release_date ? $poll->release_date->format('M d, Y') : 'N/A' }}</div>
                            </div>
                        </div>

                        <div class="border-t border-gray-100 pt-3 flex justify-between items-center text-xxs">
                            <span class="text-gray-400 font-medium font-mono">Downloads: {{ number_format($poll->initial_downloads + $poll->download_count) }}</span>
                            <span class="font-bold text-gray-900 hover:underline">View Report &rarr;</span>
                        </div>
                    </div>
                @empty
                    <div class="col-span-full bg-white border border-gray-200 rounded-lg p-12 text-center text-sm text-gray-500">
                        No public reports are available at this time.
                    </div>
                @endforelse
            </div>
        @else
            <!-- 2. DETAILED REPORT DRAWER / SCREEN -->
            <div class="bg-white border border-gray-200 rounded-lg p-8 shadow-sm grid grid-cols-1 lg:grid-cols-3 gap-8">
                <!-- Left Column: Title and Details -->
                <div class="space-y-6 lg:col-span-1">
                    <div>
                        <span class="inline-flex items-center rounded-md bg-gray-50 px-2 py-0.5 text-xs font-semibold text-gray-700 ring-1 ring-inset ring-gray-500/10 uppercase tracking-wide">
                            {{ $activeReport->category }}
                        </span>
                        <h2 class="text-xl font-bold text-gray-950 mt-2 leading-relaxed">{{ $activeReport->title }}</h2>
                    </div>

                    <!-- Meta Stats -->
                    <div class="space-y-2 text-xs text-gray-500 border-t border-b border-gray-100 py-4 font-medium">
                        <div><strong>Region Covered:</strong> {{ $activeReport->region ?? 'N/A' }}</div>
                        <div><strong>Sample Size:</strong> {{ number_format($activeReport->sample_size) }} units</div>
                        <div><strong>Research Date:</strong> {{ $activeReport->research_date ? $activeReport->research_date->format('M d, Y') : 'N/A' }}</div>
                        <div><strong>Released Date:</strong> {{ $activeReport->release_date ? $activeReport->release_date->format('M d, Y') : 'N/A' }}</div>
                        <div><strong>Total Downloads:</strong> <span class="font-bold text-gray-900">{{ number_format($activeReport->initial_downloads + $activeReport->download_count) }}</span></div>
                    </div>

                    <!-- Options & Metrics List -->
                    <div class="space-y-4 pt-2">
                        <h3 class="text-xs font-bold text-gray-900 uppercase tracking-wider">Metrics Distribution</h3>
                        @php
                            $totalVotes = collect($activeReport->options)->sum('votes');
                        @endphp
                        @foreach($activeReport->options as $opt)
                            @php
                                $pct = $totalVotes > 0 ? ($opt['votes'] / $totalVotes) * 100 : 0;
                            @endphp
                            <div class="space-y-1">
                                <div class="flex justify-between items-center text-xs font-semibold">
                                    <div class="flex items-center gap-2">
                                        <!-- Logo Display with proper container sizing -->
                                        <div class="h-6 w-6 border border-gray-100 rounded flex items-center justify-center bg-gray-50 overflow-hidden">
                                            <img src="{{ $opt['logo'] }}" class="h-4 w-4 object-contain" onerror="this.onerror=null; this.src='/favicon.png';">
                                        </div>
                                        <span class="text-gray-700">{{ $opt['name'] }}</span>
                                    </div>
                                    <span class="text-gray-950 font-mono">{{ number_format($opt['votes']) }} ({{ round($pct, 1) }}%)</span>
                                </div>
                                <div class="w-full bg-gray-100 h-1.5 rounded-full overflow-hidden">
                                    <div class="bg-gray-900 h-full rounded-full transition-all duration-300" style="width: {{ $pct }}%"></div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>

                <!-- Right Column: Research Synthesis & Gated Download -->
                <div class="lg:col-span-2 flex flex-col justify-between space-y-6 lg:border-l lg:border-gray-100 lg:pl-8">
                    <div class="space-y-4">
                        <div class="flex items-center gap-2 text-xs font-bold text-gray-500 uppercase tracking-wider">
                            <span>Research Executive Synthesis</span>
                        </div>
                        <div class="text-xs text-gray-600 leading-relaxed font-sans bg-gray-50 border border-gray-100 p-6 rounded-md overflow-y-auto max-h-96">
                            {!! nl2br(e($activeReport->ai_report)) !!}
                        </div>
                    </div>

                    <!-- Action Block -->
                    <div class="pt-4 border-t border-gray-100">
                        @if($downloadingReportId == $activeReport->id)
                            <!-- Email Form Overlay -->
                            <form wire:submit.prevent="submitDownload" class="bg-gray-50 border border-gray-200 p-4 rounded-md space-y-3">
                                <div>
                                    <label for="visitorEmail" class="block text-xs font-bold text-gray-700 uppercase">Enter email to download full brief</label>
                                    <div class="mt-1.5 flex gap-2">
                                        <input wire:model="visitorEmail" type="email" id="visitorEmail" placeholder="you@example.com" required class="block w-full rounded-md border border-gray-300 px-3 py-1.5 text-xs focus:border-gray-900 focus:outline-none bg-white">
                                        <button type="submit" class="rounded-md bg-gray-900 px-4 py-1.5 text-xs font-semibold text-white shadow-sm hover:bg-gray-800 transition">
                                            Unlock Brief
                                        </button>
                                        <button type="button" wire:click="cancelDownload" class="rounded-md border border-gray-300 bg-white px-3 py-1.5 text-xs font-semibold text-gray-700 hover:bg-gray-50">
                                            Cancel
                                        </button>
                                    </div>
                                    @error('visitorEmail') <span class="text-xxs text-red-600 mt-1 block">{{ $message }}</span> @enderror
                                </div>
                            </form>
                        @else
                            <div class="flex justify-between items-center">
                                <span class="text-xxs text-gray-400 font-semibold font-mono font-bold tracking-wider">CLASSIFICATION: PUBLIC ACCESS</span>
                                <button wire:click="downloadPrompt({{ $activeReport->id }})" class="inline-flex justify-center items-center rounded-md bg-gray-900 px-6 py-2.5 text-xs font-semibold text-white shadow-sm hover:bg-gray-800 transition">
                                    Download Research Report
                                </button>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        @endif
    </div>
</div>
